stages:
  - train

train-and-report:
  stage: train
  image: python:3.10

  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

  script:
    - python src/train.py

  artifacts:
    paths:
      - reports/
      - mlruns/
    expire_in: 7 days
